# Generated by Django 3.1.5 on 2021-05-22 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogpost',
            new_name='blog',
        ),
    ]
