# Generated by Django 3.1.5 on 2021-05-22 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210522_2250'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blog',
            new_name='Blogpost',
        ),
    ]
